// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: replacement.proto

#include "replacement.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace fira_message {
namespace sim_to_ref {
PROTOBUF_CONSTEXPR RobotReplacement::RobotReplacement(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.position_)*/nullptr
  , /*decltype(_impl_.yellowteam_)*/false
  , /*decltype(_impl_.turnon_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RobotReplacementDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RobotReplacementDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RobotReplacementDefaultTypeInternal() {}
  union {
    RobotReplacement _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RobotReplacementDefaultTypeInternal _RobotReplacement_default_instance_;
PROTOBUF_CONSTEXPR BallReplacement::BallReplacement(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.vx_)*/0
  , /*decltype(_impl_.vy_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BallReplacementDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BallReplacementDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BallReplacementDefaultTypeInternal() {}
  union {
    BallReplacement _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BallReplacementDefaultTypeInternal _BallReplacement_default_instance_;
PROTOBUF_CONSTEXPR Replacement::Replacement(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.robots_)*/{}
  , /*decltype(_impl_.ball_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReplacementDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReplacementDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReplacementDefaultTypeInternal() {}
  union {
    Replacement _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReplacementDefaultTypeInternal _Replacement_default_instance_;
}  // namespace sim_to_ref
}  // namespace fira_message
static ::_pb::Metadata file_level_metadata_replacement_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_replacement_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_replacement_2eproto = nullptr;

const uint32_t TableStruct_replacement_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fira_message::sim_to_ref::RobotReplacement, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::fira_message::sim_to_ref::RobotReplacement, _impl_.position_),
  PROTOBUF_FIELD_OFFSET(::fira_message::sim_to_ref::RobotReplacement, _impl_.yellowteam_),
  PROTOBUF_FIELD_OFFSET(::fira_message::sim_to_ref::RobotReplacement, _impl_.turnon_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fira_message::sim_to_ref::BallReplacement, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::fira_message::sim_to_ref::BallReplacement, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::fira_message::sim_to_ref::BallReplacement, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::fira_message::sim_to_ref::BallReplacement, _impl_.vx_),
  PROTOBUF_FIELD_OFFSET(::fira_message::sim_to_ref::BallReplacement, _impl_.vy_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fira_message::sim_to_ref::Replacement, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::fira_message::sim_to_ref::Replacement, _impl_.ball_),
  PROTOBUF_FIELD_OFFSET(::fira_message::sim_to_ref::Replacement, _impl_.robots_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::fira_message::sim_to_ref::RobotReplacement)},
  { 9, -1, -1, sizeof(::fira_message::sim_to_ref::BallReplacement)},
  { 19, -1, -1, sizeof(::fira_message::sim_to_ref::Replacement)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::fira_message::sim_to_ref::_RobotReplacement_default_instance_._instance,
  &::fira_message::sim_to_ref::_BallReplacement_default_instance_._instance,
  &::fira_message::sim_to_ref::_Replacement_default_instance_._instance,
};

const char descriptor_table_protodef_replacement_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021replacement.proto\022\027fira_message.sim_to"
  "_ref\032\014common.proto\"]\n\020RobotReplacement\022%"
  "\n\010position\030\001 \001(\0132\023.fira_message.Robot\022\022\n"
  "\nyellowteam\030\005 \001(\010\022\016\n\006turnon\030\006 \001(\010\"\?\n\017Bal"
  "lReplacement\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\n\n\002vx"
  "\030\003 \001(\001\022\n\n\002vy\030\004 \001(\001\"\200\001\n\013Replacement\0226\n\004ba"
  "ll\030\001 \001(\0132(.fira_message.sim_to_ref.BallR"
  "eplacement\0229\n\006robots\030\002 \003(\0132).fira_messag"
  "e.sim_to_ref.RobotReplacementb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_replacement_2eproto_deps[1] = {
  &::descriptor_table_common_2eproto,
};
static ::_pbi::once_flag descriptor_table_replacement_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_replacement_2eproto = {
    false, false, 357, descriptor_table_protodef_replacement_2eproto,
    "replacement.proto",
    &descriptor_table_replacement_2eproto_once, descriptor_table_replacement_2eproto_deps, 1, 3,
    schemas, file_default_instances, TableStruct_replacement_2eproto::offsets,
    file_level_metadata_replacement_2eproto, file_level_enum_descriptors_replacement_2eproto,
    file_level_service_descriptors_replacement_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_replacement_2eproto_getter() {
  return &descriptor_table_replacement_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_replacement_2eproto(&descriptor_table_replacement_2eproto);
namespace fira_message {
namespace sim_to_ref {

// ===================================================================

class RobotReplacement::_Internal {
 public:
  static const ::fira_message::Robot& position(const RobotReplacement* msg);
};

const ::fira_message::Robot&
RobotReplacement::_Internal::position(const RobotReplacement* msg) {
  return *msg->_impl_.position_;
}
void RobotReplacement::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
RobotReplacement::RobotReplacement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:fira_message.sim_to_ref.RobotReplacement)
}
RobotReplacement::RobotReplacement(const RobotReplacement& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RobotReplacement* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){nullptr}
    , decltype(_impl_.yellowteam_){}
    , decltype(_impl_.turnon_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_position()) {
    _this->_impl_.position_ = new ::fira_message::Robot(*from._impl_.position_);
  }
  ::memcpy(&_impl_.yellowteam_, &from._impl_.yellowteam_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.turnon_) -
    reinterpret_cast<char*>(&_impl_.yellowteam_)) + sizeof(_impl_.turnon_));
  // @@protoc_insertion_point(copy_constructor:fira_message.sim_to_ref.RobotReplacement)
}

inline void RobotReplacement::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){nullptr}
    , decltype(_impl_.yellowteam_){false}
    , decltype(_impl_.turnon_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RobotReplacement::~RobotReplacement() {
  // @@protoc_insertion_point(destructor:fira_message.sim_to_ref.RobotReplacement)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RobotReplacement::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.position_;
}

void RobotReplacement::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RobotReplacement::Clear() {
// @@protoc_insertion_point(message_clear_start:fira_message.sim_to_ref.RobotReplacement)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
  ::memset(&_impl_.yellowteam_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.turnon_) -
      reinterpret_cast<char*>(&_impl_.yellowteam_)) + sizeof(_impl_.turnon_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RobotReplacement::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .fira_message.Robot position = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool yellowteam = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.yellowteam_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool turnon = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.turnon_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RobotReplacement::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fira_message.sim_to_ref.RobotReplacement)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .fira_message.Robot position = 1;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  // bool yellowteam = 5;
  if (this->_internal_yellowteam() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_yellowteam(), target);
  }

  // bool turnon = 6;
  if (this->_internal_turnon() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(6, this->_internal_turnon(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fira_message.sim_to_ref.RobotReplacement)
  return target;
}

size_t RobotReplacement::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fira_message.sim_to_ref.RobotReplacement)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .fira_message.Robot position = 1;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.position_);
  }

  // bool yellowteam = 5;
  if (this->_internal_yellowteam() != 0) {
    total_size += 1 + 1;
  }

  // bool turnon = 6;
  if (this->_internal_turnon() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RobotReplacement::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RobotReplacement::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RobotReplacement::GetClassData() const { return &_class_data_; }


void RobotReplacement::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RobotReplacement*>(&to_msg);
  auto& from = static_cast<const RobotReplacement&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:fira_message.sim_to_ref.RobotReplacement)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_position()) {
    _this->_internal_mutable_position()->::fira_message::Robot::MergeFrom(
        from._internal_position());
  }
  if (from._internal_yellowteam() != 0) {
    _this->_internal_set_yellowteam(from._internal_yellowteam());
  }
  if (from._internal_turnon() != 0) {
    _this->_internal_set_turnon(from._internal_turnon());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RobotReplacement::CopyFrom(const RobotReplacement& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fira_message.sim_to_ref.RobotReplacement)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RobotReplacement::IsInitialized() const {
  return true;
}

void RobotReplacement::InternalSwap(RobotReplacement* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RobotReplacement, _impl_.turnon_)
      + sizeof(RobotReplacement::_impl_.turnon_)
      - PROTOBUF_FIELD_OFFSET(RobotReplacement, _impl_.position_)>(
          reinterpret_cast<char*>(&_impl_.position_),
          reinterpret_cast<char*>(&other->_impl_.position_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RobotReplacement::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_replacement_2eproto_getter, &descriptor_table_replacement_2eproto_once,
      file_level_metadata_replacement_2eproto[0]);
}

// ===================================================================

class BallReplacement::_Internal {
 public:
};

BallReplacement::BallReplacement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:fira_message.sim_to_ref.BallReplacement)
}
BallReplacement::BallReplacement(const BallReplacement& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BallReplacement* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.vx_){}
    , decltype(_impl_.vy_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.x_, &from._impl_.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.vy_) -
    reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.vy_));
  // @@protoc_insertion_point(copy_constructor:fira_message.sim_to_ref.BallReplacement)
}

inline void BallReplacement::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.vx_){0}
    , decltype(_impl_.vy_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BallReplacement::~BallReplacement() {
  // @@protoc_insertion_point(destructor:fira_message.sim_to_ref.BallReplacement)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BallReplacement::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BallReplacement::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BallReplacement::Clear() {
// @@protoc_insertion_point(message_clear_start:fira_message.sim_to_ref.BallReplacement)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.vy_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.vy_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BallReplacement::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double vx = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.vx_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double vy = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.vy_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BallReplacement::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fira_message.sim_to_ref.BallReplacement)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double x = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = this->_internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_x(), target);
  }

  // double y = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = this->_internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_y(), target);
  }

  // double vx = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_vx = this->_internal_vx();
  uint64_t raw_vx;
  memcpy(&raw_vx, &tmp_vx, sizeof(tmp_vx));
  if (raw_vx != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_vx(), target);
  }

  // double vy = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_vy = this->_internal_vy();
  uint64_t raw_vy;
  memcpy(&raw_vy, &tmp_vy, sizeof(tmp_vy));
  if (raw_vy != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_vy(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fira_message.sim_to_ref.BallReplacement)
  return target;
}

size_t BallReplacement::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fira_message.sim_to_ref.BallReplacement)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double x = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = this->_internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 1 + 8;
  }

  // double y = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = this->_internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 1 + 8;
  }

  // double vx = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_vx = this->_internal_vx();
  uint64_t raw_vx;
  memcpy(&raw_vx, &tmp_vx, sizeof(tmp_vx));
  if (raw_vx != 0) {
    total_size += 1 + 8;
  }

  // double vy = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_vy = this->_internal_vy();
  uint64_t raw_vy;
  memcpy(&raw_vy, &tmp_vy, sizeof(tmp_vy));
  if (raw_vy != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BallReplacement::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BallReplacement::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BallReplacement::GetClassData() const { return &_class_data_; }


void BallReplacement::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BallReplacement*>(&to_msg);
  auto& from = static_cast<const BallReplacement&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:fira_message.sim_to_ref.BallReplacement)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_x = from._internal_x();
  uint64_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_y = from._internal_y();
  uint64_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_vx = from._internal_vx();
  uint64_t raw_vx;
  memcpy(&raw_vx, &tmp_vx, sizeof(tmp_vx));
  if (raw_vx != 0) {
    _this->_internal_set_vx(from._internal_vx());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_vy = from._internal_vy();
  uint64_t raw_vy;
  memcpy(&raw_vy, &tmp_vy, sizeof(tmp_vy));
  if (raw_vy != 0) {
    _this->_internal_set_vy(from._internal_vy());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BallReplacement::CopyFrom(const BallReplacement& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fira_message.sim_to_ref.BallReplacement)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BallReplacement::IsInitialized() const {
  return true;
}

void BallReplacement::InternalSwap(BallReplacement* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BallReplacement, _impl_.vy_)
      + sizeof(BallReplacement::_impl_.vy_)
      - PROTOBUF_FIELD_OFFSET(BallReplacement, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata BallReplacement::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_replacement_2eproto_getter, &descriptor_table_replacement_2eproto_once,
      file_level_metadata_replacement_2eproto[1]);
}

// ===================================================================

class Replacement::_Internal {
 public:
  static const ::fira_message::sim_to_ref::BallReplacement& ball(const Replacement* msg);
};

const ::fira_message::sim_to_ref::BallReplacement&
Replacement::_Internal::ball(const Replacement* msg) {
  return *msg->_impl_.ball_;
}
Replacement::Replacement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:fira_message.sim_to_ref.Replacement)
}
Replacement::Replacement(const Replacement& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Replacement* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.robots_){from._impl_.robots_}
    , decltype(_impl_.ball_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_ball()) {
    _this->_impl_.ball_ = new ::fira_message::sim_to_ref::BallReplacement(*from._impl_.ball_);
  }
  // @@protoc_insertion_point(copy_constructor:fira_message.sim_to_ref.Replacement)
}

inline void Replacement::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.robots_){arena}
    , decltype(_impl_.ball_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Replacement::~Replacement() {
  // @@protoc_insertion_point(destructor:fira_message.sim_to_ref.Replacement)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Replacement::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.robots_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.ball_;
}

void Replacement::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Replacement::Clear() {
// @@protoc_insertion_point(message_clear_start:fira_message.sim_to_ref.Replacement)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.robots_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.ball_ != nullptr) {
    delete _impl_.ball_;
  }
  _impl_.ball_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Replacement::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .fira_message.sim_to_ref.BallReplacement ball = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_ball(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .fira_message.sim_to_ref.RobotReplacement robots = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_robots(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Replacement::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fira_message.sim_to_ref.Replacement)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .fira_message.sim_to_ref.BallReplacement ball = 1;
  if (this->_internal_has_ball()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::ball(this),
        _Internal::ball(this).GetCachedSize(), target, stream);
  }

  // repeated .fira_message.sim_to_ref.RobotReplacement robots = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_robots_size()); i < n; i++) {
    const auto& repfield = this->_internal_robots(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fira_message.sim_to_ref.Replacement)
  return target;
}

size_t Replacement::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fira_message.sim_to_ref.Replacement)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .fira_message.sim_to_ref.RobotReplacement robots = 2;
  total_size += 1UL * this->_internal_robots_size();
  for (const auto& msg : this->_impl_.robots_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .fira_message.sim_to_ref.BallReplacement ball = 1;
  if (this->_internal_has_ball()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.ball_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Replacement::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Replacement::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Replacement::GetClassData() const { return &_class_data_; }


void Replacement::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Replacement*>(&to_msg);
  auto& from = static_cast<const Replacement&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:fira_message.sim_to_ref.Replacement)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.robots_.MergeFrom(from._impl_.robots_);
  if (from._internal_has_ball()) {
    _this->_internal_mutable_ball()->::fira_message::sim_to_ref::BallReplacement::MergeFrom(
        from._internal_ball());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Replacement::CopyFrom(const Replacement& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fira_message.sim_to_ref.Replacement)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Replacement::IsInitialized() const {
  return true;
}

void Replacement::InternalSwap(Replacement* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.robots_.InternalSwap(&other->_impl_.robots_);
  swap(_impl_.ball_, other->_impl_.ball_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Replacement::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_replacement_2eproto_getter, &descriptor_table_replacement_2eproto_once,
      file_level_metadata_replacement_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace sim_to_ref
}  // namespace fira_message
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::fira_message::sim_to_ref::RobotReplacement*
Arena::CreateMaybeMessage< ::fira_message::sim_to_ref::RobotReplacement >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fira_message::sim_to_ref::RobotReplacement >(arena);
}
template<> PROTOBUF_NOINLINE ::fira_message::sim_to_ref::BallReplacement*
Arena::CreateMaybeMessage< ::fira_message::sim_to_ref::BallReplacement >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fira_message::sim_to_ref::BallReplacement >(arena);
}
template<> PROTOBUF_NOINLINE ::fira_message::sim_to_ref::Replacement*
Arena::CreateMaybeMessage< ::fira_message::sim_to_ref::Replacement >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fira_message::sim_to_ref::Replacement >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
