// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: replacement.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_replacement_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_replacement_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_replacement_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_replacement_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_replacement_2eproto;
namespace fira_message {
namespace sim_to_ref {
class BallReplacement;
struct BallReplacementDefaultTypeInternal;
extern BallReplacementDefaultTypeInternal _BallReplacement_default_instance_;
class Replacement;
struct ReplacementDefaultTypeInternal;
extern ReplacementDefaultTypeInternal _Replacement_default_instance_;
class RobotReplacement;
struct RobotReplacementDefaultTypeInternal;
extern RobotReplacementDefaultTypeInternal _RobotReplacement_default_instance_;
}  // namespace sim_to_ref
}  // namespace fira_message
PROTOBUF_NAMESPACE_OPEN
template<> ::fira_message::sim_to_ref::BallReplacement* Arena::CreateMaybeMessage<::fira_message::sim_to_ref::BallReplacement>(Arena*);
template<> ::fira_message::sim_to_ref::Replacement* Arena::CreateMaybeMessage<::fira_message::sim_to_ref::Replacement>(Arena*);
template<> ::fira_message::sim_to_ref::RobotReplacement* Arena::CreateMaybeMessage<::fira_message::sim_to_ref::RobotReplacement>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace fira_message {
namespace sim_to_ref {

// ===================================================================

class RobotReplacement final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.RobotReplacement) */ {
 public:
  inline RobotReplacement() : RobotReplacement(nullptr) {}
  ~RobotReplacement() override;
  explicit PROTOBUF_CONSTEXPR RobotReplacement(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RobotReplacement(const RobotReplacement& from);
  RobotReplacement(RobotReplacement&& from) noexcept
    : RobotReplacement() {
    *this = ::std::move(from);
  }

  inline RobotReplacement& operator=(const RobotReplacement& from) {
    CopyFrom(from);
    return *this;
  }
  inline RobotReplacement& operator=(RobotReplacement&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RobotReplacement& default_instance() {
    return *internal_default_instance();
  }
  static inline const RobotReplacement* internal_default_instance() {
    return reinterpret_cast<const RobotReplacement*>(
               &_RobotReplacement_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RobotReplacement& a, RobotReplacement& b) {
    a.Swap(&b);
  }
  inline void Swap(RobotReplacement* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RobotReplacement* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RobotReplacement* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RobotReplacement>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RobotReplacement& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RobotReplacement& from) {
    RobotReplacement::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RobotReplacement* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fira_message.sim_to_ref.RobotReplacement";
  }
  protected:
  explicit RobotReplacement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kYellowteamFieldNumber = 5,
    kTurnonFieldNumber = 6,
  };
  // .fira_message.Robot position = 1;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::fira_message::Robot& position() const;
  PROTOBUF_NODISCARD ::fira_message::Robot* release_position();
  ::fira_message::Robot* mutable_position();
  void set_allocated_position(::fira_message::Robot* position);
  private:
  const ::fira_message::Robot& _internal_position() const;
  ::fira_message::Robot* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::fira_message::Robot* position);
  ::fira_message::Robot* unsafe_arena_release_position();

  // bool yellowteam = 5;
  void clear_yellowteam();
  bool yellowteam() const;
  void set_yellowteam(bool value);
  private:
  bool _internal_yellowteam() const;
  void _internal_set_yellowteam(bool value);
  public:

  // bool turnon = 6;
  void clear_turnon();
  bool turnon() const;
  void set_turnon(bool value);
  private:
  bool _internal_turnon() const;
  void _internal_set_turnon(bool value);
  public:

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.RobotReplacement)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::fira_message::Robot* position_;
    bool yellowteam_;
    bool turnon_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_replacement_2eproto;
};
// -------------------------------------------------------------------

class BallReplacement final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.BallReplacement) */ {
 public:
  inline BallReplacement() : BallReplacement(nullptr) {}
  ~BallReplacement() override;
  explicit PROTOBUF_CONSTEXPR BallReplacement(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BallReplacement(const BallReplacement& from);
  BallReplacement(BallReplacement&& from) noexcept
    : BallReplacement() {
    *this = ::std::move(from);
  }

  inline BallReplacement& operator=(const BallReplacement& from) {
    CopyFrom(from);
    return *this;
  }
  inline BallReplacement& operator=(BallReplacement&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BallReplacement& default_instance() {
    return *internal_default_instance();
  }
  static inline const BallReplacement* internal_default_instance() {
    return reinterpret_cast<const BallReplacement*>(
               &_BallReplacement_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BallReplacement& a, BallReplacement& b) {
    a.Swap(&b);
  }
  inline void Swap(BallReplacement* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BallReplacement* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BallReplacement* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BallReplacement>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BallReplacement& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BallReplacement& from) {
    BallReplacement::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BallReplacement* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fira_message.sim_to_ref.BallReplacement";
  }
  protected:
  explicit BallReplacement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kVxFieldNumber = 3,
    kVyFieldNumber = 4,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double vx = 3;
  void clear_vx();
  double vx() const;
  void set_vx(double value);
  private:
  double _internal_vx() const;
  void _internal_set_vx(double value);
  public:

  // double vy = 4;
  void clear_vy();
  double vy() const;
  void set_vy(double value);
  private:
  double _internal_vy() const;
  void _internal_set_vy(double value);
  public:

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.BallReplacement)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double x_;
    double y_;
    double vx_;
    double vy_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_replacement_2eproto;
};
// -------------------------------------------------------------------

class Replacement final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.Replacement) */ {
 public:
  inline Replacement() : Replacement(nullptr) {}
  ~Replacement() override;
  explicit PROTOBUF_CONSTEXPR Replacement(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Replacement(const Replacement& from);
  Replacement(Replacement&& from) noexcept
    : Replacement() {
    *this = ::std::move(from);
  }

  inline Replacement& operator=(const Replacement& from) {
    CopyFrom(from);
    return *this;
  }
  inline Replacement& operator=(Replacement&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Replacement& default_instance() {
    return *internal_default_instance();
  }
  static inline const Replacement* internal_default_instance() {
    return reinterpret_cast<const Replacement*>(
               &_Replacement_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Replacement& a, Replacement& b) {
    a.Swap(&b);
  }
  inline void Swap(Replacement* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Replacement* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Replacement* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Replacement>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Replacement& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Replacement& from) {
    Replacement::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Replacement* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fira_message.sim_to_ref.Replacement";
  }
  protected:
  explicit Replacement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRobotsFieldNumber = 2,
    kBallFieldNumber = 1,
  };
  // repeated .fira_message.sim_to_ref.RobotReplacement robots = 2;
  int robots_size() const;
  private:
  int _internal_robots_size() const;
  public:
  void clear_robots();
  ::fira_message::sim_to_ref::RobotReplacement* mutable_robots(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement >*
      mutable_robots();
  private:
  const ::fira_message::sim_to_ref::RobotReplacement& _internal_robots(int index) const;
  ::fira_message::sim_to_ref::RobotReplacement* _internal_add_robots();
  public:
  const ::fira_message::sim_to_ref::RobotReplacement& robots(int index) const;
  ::fira_message::sim_to_ref::RobotReplacement* add_robots();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement >&
      robots() const;

  // .fira_message.sim_to_ref.BallReplacement ball = 1;
  bool has_ball() const;
  private:
  bool _internal_has_ball() const;
  public:
  void clear_ball();
  const ::fira_message::sim_to_ref::BallReplacement& ball() const;
  PROTOBUF_NODISCARD ::fira_message::sim_to_ref::BallReplacement* release_ball();
  ::fira_message::sim_to_ref::BallReplacement* mutable_ball();
  void set_allocated_ball(::fira_message::sim_to_ref::BallReplacement* ball);
  private:
  const ::fira_message::sim_to_ref::BallReplacement& _internal_ball() const;
  ::fira_message::sim_to_ref::BallReplacement* _internal_mutable_ball();
  public:
  void unsafe_arena_set_allocated_ball(
      ::fira_message::sim_to_ref::BallReplacement* ball);
  ::fira_message::sim_to_ref::BallReplacement* unsafe_arena_release_ball();

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.Replacement)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement > robots_;
    ::fira_message::sim_to_ref::BallReplacement* ball_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_replacement_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RobotReplacement

// .fira_message.Robot position = 1;
inline bool RobotReplacement::_internal_has_position() const {
  return this != internal_default_instance() && _impl_.position_ != nullptr;
}
inline bool RobotReplacement::has_position() const {
  return _internal_has_position();
}
inline const ::fira_message::Robot& RobotReplacement::_internal_position() const {
  const ::fira_message::Robot* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::fira_message::Robot&>(
      ::fira_message::_Robot_default_instance_);
}
inline const ::fira_message::Robot& RobotReplacement::position() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.RobotReplacement.position)
  return _internal_position();
}
inline void RobotReplacement::unsafe_arena_set_allocated_position(
    ::fira_message::Robot* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fira_message.sim_to_ref.RobotReplacement.position)
}
inline ::fira_message::Robot* RobotReplacement::release_position() {
  
  ::fira_message::Robot* temp = _impl_.position_;
  _impl_.position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::fira_message::Robot* RobotReplacement::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:fira_message.sim_to_ref.RobotReplacement.position)
  
  ::fira_message::Robot* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::fira_message::Robot* RobotReplacement::_internal_mutable_position() {
  
  if (_impl_.position_ == nullptr) {
    auto* p = CreateMaybeMessage<::fira_message::Robot>(GetArenaForAllocation());
    _impl_.position_ = p;
  }
  return _impl_.position_;
}
inline ::fira_message::Robot* RobotReplacement::mutable_position() {
  ::fira_message::Robot* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.RobotReplacement.position)
  return _msg;
}
inline void RobotReplacement::set_allocated_position(::fira_message::Robot* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position));
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.position_ = position;
  // @@protoc_insertion_point(field_set_allocated:fira_message.sim_to_ref.RobotReplacement.position)
}

// bool yellowteam = 5;
inline void RobotReplacement::clear_yellowteam() {
  _impl_.yellowteam_ = false;
}
inline bool RobotReplacement::_internal_yellowteam() const {
  return _impl_.yellowteam_;
}
inline bool RobotReplacement::yellowteam() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.RobotReplacement.yellowteam)
  return _internal_yellowteam();
}
inline void RobotReplacement::_internal_set_yellowteam(bool value) {
  
  _impl_.yellowteam_ = value;
}
inline void RobotReplacement::set_yellowteam(bool value) {
  _internal_set_yellowteam(value);
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.RobotReplacement.yellowteam)
}

// bool turnon = 6;
inline void RobotReplacement::clear_turnon() {
  _impl_.turnon_ = false;
}
inline bool RobotReplacement::_internal_turnon() const {
  return _impl_.turnon_;
}
inline bool RobotReplacement::turnon() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.RobotReplacement.turnon)
  return _internal_turnon();
}
inline void RobotReplacement::_internal_set_turnon(bool value) {
  
  _impl_.turnon_ = value;
}
inline void RobotReplacement::set_turnon(bool value) {
  _internal_set_turnon(value);
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.RobotReplacement.turnon)
}

// -------------------------------------------------------------------

// BallReplacement

// double x = 1;
inline void BallReplacement::clear_x() {
  _impl_.x_ = 0;
}
inline double BallReplacement::_internal_x() const {
  return _impl_.x_;
}
inline double BallReplacement::x() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.BallReplacement.x)
  return _internal_x();
}
inline void BallReplacement::_internal_set_x(double value) {
  
  _impl_.x_ = value;
}
inline void BallReplacement::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.BallReplacement.x)
}

// double y = 2;
inline void BallReplacement::clear_y() {
  _impl_.y_ = 0;
}
inline double BallReplacement::_internal_y() const {
  return _impl_.y_;
}
inline double BallReplacement::y() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.BallReplacement.y)
  return _internal_y();
}
inline void BallReplacement::_internal_set_y(double value) {
  
  _impl_.y_ = value;
}
inline void BallReplacement::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.BallReplacement.y)
}

// double vx = 3;
inline void BallReplacement::clear_vx() {
  _impl_.vx_ = 0;
}
inline double BallReplacement::_internal_vx() const {
  return _impl_.vx_;
}
inline double BallReplacement::vx() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.BallReplacement.vx)
  return _internal_vx();
}
inline void BallReplacement::_internal_set_vx(double value) {
  
  _impl_.vx_ = value;
}
inline void BallReplacement::set_vx(double value) {
  _internal_set_vx(value);
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.BallReplacement.vx)
}

// double vy = 4;
inline void BallReplacement::clear_vy() {
  _impl_.vy_ = 0;
}
inline double BallReplacement::_internal_vy() const {
  return _impl_.vy_;
}
inline double BallReplacement::vy() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.BallReplacement.vy)
  return _internal_vy();
}
inline void BallReplacement::_internal_set_vy(double value) {
  
  _impl_.vy_ = value;
}
inline void BallReplacement::set_vy(double value) {
  _internal_set_vy(value);
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.BallReplacement.vy)
}

// -------------------------------------------------------------------

// Replacement

// .fira_message.sim_to_ref.BallReplacement ball = 1;
inline bool Replacement::_internal_has_ball() const {
  return this != internal_default_instance() && _impl_.ball_ != nullptr;
}
inline bool Replacement::has_ball() const {
  return _internal_has_ball();
}
inline void Replacement::clear_ball() {
  if (GetArenaForAllocation() == nullptr && _impl_.ball_ != nullptr) {
    delete _impl_.ball_;
  }
  _impl_.ball_ = nullptr;
}
inline const ::fira_message::sim_to_ref::BallReplacement& Replacement::_internal_ball() const {
  const ::fira_message::sim_to_ref::BallReplacement* p = _impl_.ball_;
  return p != nullptr ? *p : reinterpret_cast<const ::fira_message::sim_to_ref::BallReplacement&>(
      ::fira_message::sim_to_ref::_BallReplacement_default_instance_);
}
inline const ::fira_message::sim_to_ref::BallReplacement& Replacement::ball() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Replacement.ball)
  return _internal_ball();
}
inline void Replacement::unsafe_arena_set_allocated_ball(
    ::fira_message::sim_to_ref::BallReplacement* ball) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.ball_);
  }
  _impl_.ball_ = ball;
  if (ball) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fira_message.sim_to_ref.Replacement.ball)
}
inline ::fira_message::sim_to_ref::BallReplacement* Replacement::release_ball() {
  
  ::fira_message::sim_to_ref::BallReplacement* temp = _impl_.ball_;
  _impl_.ball_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::fira_message::sim_to_ref::BallReplacement* Replacement::unsafe_arena_release_ball() {
  // @@protoc_insertion_point(field_release:fira_message.sim_to_ref.Replacement.ball)
  
  ::fira_message::sim_to_ref::BallReplacement* temp = _impl_.ball_;
  _impl_.ball_ = nullptr;
  return temp;
}
inline ::fira_message::sim_to_ref::BallReplacement* Replacement::_internal_mutable_ball() {
  
  if (_impl_.ball_ == nullptr) {
    auto* p = CreateMaybeMessage<::fira_message::sim_to_ref::BallReplacement>(GetArenaForAllocation());
    _impl_.ball_ = p;
  }
  return _impl_.ball_;
}
inline ::fira_message::sim_to_ref::BallReplacement* Replacement::mutable_ball() {
  ::fira_message::sim_to_ref::BallReplacement* _msg = _internal_mutable_ball();
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.Replacement.ball)
  return _msg;
}
inline void Replacement::set_allocated_ball(::fira_message::sim_to_ref::BallReplacement* ball) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.ball_;
  }
  if (ball) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(ball);
    if (message_arena != submessage_arena) {
      ball = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ball, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.ball_ = ball;
  // @@protoc_insertion_point(field_set_allocated:fira_message.sim_to_ref.Replacement.ball)
}

// repeated .fira_message.sim_to_ref.RobotReplacement robots = 2;
inline int Replacement::_internal_robots_size() const {
  return _impl_.robots_.size();
}
inline int Replacement::robots_size() const {
  return _internal_robots_size();
}
inline void Replacement::clear_robots() {
  _impl_.robots_.Clear();
}
inline ::fira_message::sim_to_ref::RobotReplacement* Replacement::mutable_robots(int index) {
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.Replacement.robots)
  return _impl_.robots_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement >*
Replacement::mutable_robots() {
  // @@protoc_insertion_point(field_mutable_list:fira_message.sim_to_ref.Replacement.robots)
  return &_impl_.robots_;
}
inline const ::fira_message::sim_to_ref::RobotReplacement& Replacement::_internal_robots(int index) const {
  return _impl_.robots_.Get(index);
}
inline const ::fira_message::sim_to_ref::RobotReplacement& Replacement::robots(int index) const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Replacement.robots)
  return _internal_robots(index);
}
inline ::fira_message::sim_to_ref::RobotReplacement* Replacement::_internal_add_robots() {
  return _impl_.robots_.Add();
}
inline ::fira_message::sim_to_ref::RobotReplacement* Replacement::add_robots() {
  ::fira_message::sim_to_ref::RobotReplacement* _add = _internal_add_robots();
  // @@protoc_insertion_point(field_add:fira_message.sim_to_ref.Replacement.robots)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement >&
Replacement::robots() const {
  // @@protoc_insertion_point(field_list:fira_message.sim_to_ref.Replacement.robots)
  return _impl_.robots_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sim_to_ref
}  // namespace fira_message

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_replacement_2eproto
